/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UfOgAiaPqgO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function ui-component() {
  return (
    <div className="flex min-h-[100dvh] flex-col bg-background text-foreground">
      <header className="flex items-center justify-between px-4 py-3 sm:px-6 lg:px-8">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <GraduationCapIcon className="h-6 w-6" />
          <span className="text-xl font-bold">Campus Connect</span>
        </Link>
        <div className="flex items-center gap-4">
          <Link
            href="#"
            className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
          >
            Sign Up
          </Link>
          <Link
            href="#"
            className="rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
          >
            Log In
          </Link>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-gradient-to-r from-[#6c5ce7] to-[#a29bfe] py-12 sm:py-16 lg:py-20">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 gap-8 lg:grid-cols-2 lg:gap-16">
              <div className="flex flex-col items-start justify-center">
                <h1 className="text-3xl font-bold tracking-tight text-primary-foreground sm:text-4xl lg:text-5xl">
                  Connect, Discover, and Thrive
                </h1>
                <p className="mt-4 text-lg text-primary-foreground">
                  Campus Connect is the ultimate student social network, helping you build meaningful connections,
                  discover new opportunities, and unlock your full potential.
                </p>
                <div className="mt-6 flex items-center gap-4">
                  <Link
                    href="#"
                    className="inline-flex items-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Join Now
                  </Link>
                  <Link
                    href="#"
                    className="text-sm font-medium text-primary-foreground hover:underline"
                    prefetch={false}
                  >
                    Learn More
                  </Link>
                </div>
              </div>
              <div className="flex justify-center">
                <img
                  src="/placeholder.svg"
                  width={500}
                  height={500}
                  alt="Campus Connect"
                  className="rounded-xl object-cover"
                  style={{ aspectRatio: "500/500", objectFit: "cover" }}
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 sm:py-16 lg:py-20">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 gap-8 lg:grid-cols-2 lg:gap-16">
              <div className="flex justify-center">
                <img
                  src="/placeholder.svg"
                  width={500}
                  height={500}
                  alt="Campus Community"
                  className="rounded-xl object-cover"
                  style={{ aspectRatio: "500/500", objectFit: "cover" }}
                />
              </div>
              <div className="flex flex-col items-start justify-center">
                <h2 className="text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl">
                  Build Your Campus Community
                </h2>
                <p className="mt-4 text-lg text-muted-foreground">
                  Connect with like-minded students, join clubs and organizations, and discover new opportunities to get
                  involved on campus.
                </p>
                <div className="mt-6 flex items-center gap-4">
                  <Link
                    href="#"
                    className="inline-flex items-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Explore Campus
                  </Link>
                  <Link href="#" className="text-sm font-medium text-primary hover:underline" prefetch={false}>
                    Learn More
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 sm:py-16 lg:py-20">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 gap-8 lg:grid-cols-2 lg:gap-16">
              <div className="flex flex-col items-start justify-center">
                <h2 className="text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl">Unlock Your Potential</h2>
                <p className="mt-4 text-lg text-muted-foreground">
                  Discover new interests, find mentors, and access resources to help you grow and succeed in your
                  academic and personal life.
                </p>
                <div className="mt-6 flex items-center gap-4">
                  <Link
                    href="#"
                    className="inline-flex items-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Join Now
                  </Link>
                  <Link href="#" className="text-sm font-medium text-primary hover:underline" prefetch={false}>
                    Learn More
                  </Link>
                </div>
              </div>
              <div className="flex justify-center">
                <img
                  src="/placeholder.svg"
                  width={500}
                  height={500}
                  alt="Unlock Your Potential"
                  className="rounded-xl object-cover"
                  style={{ aspectRatio: "500/500", objectFit: "cover" }}
                />
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-6 sm:py-8 lg:py-10">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
            <p className="text-sm text-muted-foreground">&copy; 2024 Campus Connect. All rights reserved.</p>
            <nav className="flex items-center gap-4">
              <Link
                href="#"
                className="text-sm font-medium text-muted-foreground hover:text-foreground"
                prefetch={false}
              >
                Privacy Policy
              </Link>
              <Link
                href="#"
                className="text-sm font-medium text-muted-foreground hover:text-foreground"
                prefetch={false}
              >
                Terms of Service
              </Link>
              <Link
                href="#"
                className="text-sm font-medium text-muted-foreground hover:text-foreground"
                prefetch={false}
              >
                Contact Us
              </Link>
            </nav>
          </div>
        </div>
      </footer>
    </div>
  )
}

function GraduationCapIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z" />
      <path d="M22 10v6" />
      <path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5" />
    </svg>
  )
}
